config/routes.rb
Rails.application.routes.draw do
  root  :to => 'top#top'
  get    'maps/index'
  get    'posts/index'
  post   'guest_login',                     to: 'guest_sessions#create'
  post   '/search',                         to: 'search#search'
  get    '/login',                          to: 'sessions#new'
  post   '/login',                          to: 'sessions#create'
  delete '/logout',                         to: 'sessions#destroy'
  get    '/users/account',                  to: 'users#account'
  get    '/users/profile',                  to: 'users#profile'
  post   '/users/profile_update',           to: 'users#profile_update'
  get    '/users/edit',                     to: 'users#edit'
  post   '/users/update',                   to: 'users#update'
  get    '/posts/:id/index',                to: 'posts#edit_index'

  resources :users
  resources :posts
  resources :maps, only: [:show]
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    gon.map_key = ENV['Google_Map_API']
    @posts = Post.search(params[:keyword])
    if @posts.count.zero?
      flash[:notice] = '検索結果がありませんでした'
      redirect_to root_path
    elsif params[:sort_update]
      @posts = Post.search(params[:keyword]).latest
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<h1 class="post_top_title">検索結果</h1>
<div class="sort_area">
  <%= link_to '投稿順でソートする', search_path(keyword: "#{params[:keyword]}"), method: :post , class: "sort_button" %>
  <%= link_to '新着順でソートする', search_path(sort_update: "true", keyword: "#{params[:keyword]}"), method: :post, class: "sort_button" %>
</div>
<div class="container"id="post_index">
  <% @posts.each do |post| %>
  <div class="post_container">
    <div class="post_inner">
        <div class="post_form">
          <div class="post_title">タイトル</div>
          <%= post.title %>
        </div>
        <div class="post_form" id="post_image_form">
          <%= image_tag post.image, class:"post_image" %>
        </div>
        <div class="post_form">
          <div class="post_title">投稿日時</div>
          <%= post.created_at.strftime('%Y/%m/%d %H:%M') %>
        </div>
        <div class="post_form">
          <div class="post_title">発見場所</div>
          <%= post.place_prefecture %>
          <%= post.place_detail %>
        </div>
        <div class="post_form">
          <div class="post_title">状況詳細</div>
          <%= post.description %>
        </div>
        <div class="post_form">
          <%= link_to "地図で場所を確認する", map_path(post.id) %>
        </div>
    </div>
  </div>
  <% end %>
  <script>
    function connectGoogleMap(){
      var key = gon.map_key
      var sc = document.createElement('script');
      sc.src = `https://maps.googleapis.com/maps/api/js?key=${key}&langage=ja`;
      document.body.appendChild(sc);
    };
    connectGoogleMap();
  </script>
</div>