config/routes.rb
Rails.application.routes.draw do
  root  :to => 'top#top'
  get    'maps/index'
  get    'posts/index'
  post   'guest_login',                     to: 'guest_sessions#create'
  post   '/search',                         to: 'search#search'
  get    '/login',                          to: 'sessions#new'
  post   '/login',                          to: 'sessions#create'
  delete '/logout',                         to: 'sessions#destroy'
  get    '/users/account',                  to: 'users#account'
  get    '/users/profile',                  to: 'users#profile'
  post   '/users/profile_update',           to: 'users#profile_update'
  get    '/users/edit',                     to: 'users#edit'
  post   '/users/update',                   to: 'users#update'
  get    '/posts/:id/index',                to: 'posts#edit_index'

  resources :users
  resources :posts
  resources :maps, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, length: { in: 6..20 }, on: :create
  has_many :post, dependent: :destroy

  has_one_attached :avatar
  has_secure_password

  before_create :set_current_password
  before_update :update_current_password

  def set_current_password
    self.current_password = password_digest
  end

  def update_current_password
    self.current_password = password_digest
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include GuestSessionsHelper
  before_action :logged_in_user, only: %i[account profile edit profile_update update]
  before_action :forbid_login_user, only: %i[new create]
  before_action :guest_check, only: %i[profile_update update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'ユーザー登録が完了しました'
      redirect_to :root
    else
      render 'users/new', status: :unprocessable_entity
    end
  end

  def account; end

  def profile
    @user = User.find(@current_user.id)
  end

  def edit
    @user = User.find(@current_user.id)
  end

  def profile_update
    @user = User.find(@current_user.id)
    if @user.update(user_params)
      flash[:notice] = 'プロフィール情報を更新しました'
      redirect_to :root
    else
      @user = User.new(user_params)
      flash[:notice] = '更新に失敗しました'
      render 'users/profile', status: :unprocessable_entity
    end
  end

  def update
    @user = User.find(@current_user.id)
    if params[:user][:password] == params[:user][:password_confirmation]
      if @user.authenticate(params[:user][:current_password])\
         && @user.authenticate(params[:user][:current_password]).password_digest == @user.current_password
        if @user.update(user_params)
          flash[:notice] = 'ユーザー情報を更新しました'
          redirect_to :users_profile
        else
          @user = User.new(user_params)
          flash[:notice] = '更新に失敗しました'
          render 'users/edit', status: :unprocessable_entity
        end
      else
        flash[:notice] = '現在のパスワードを正しく入力してください'
        render 'users/edit', status: :unprocessable_entity
      end
    else
      flash[:notice] = '変更するパスワードを正しく入力してください'
      render 'users/edit', status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(@current_user.id)
    @user.destroy
    flash[:notice] = 'アカウントを削除しました'
    redirect_to root_path
  end

  private

  def user_params
    params
      .require(:user)
      .permit(
        :name, :email, :introduction,
        :password, :password_confirmation, :current_password, :avatar
      )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div id="user_setting_container">
  <div class="sidebar">
    <ul>
      <li class="mark">
        <%= link_to "アカウント", :users_account %>
      </li>
      <li>
        <%= link_to "プロフィール", :users_profile %>
      </li>
    </ul>
  </div>
  <div class="main">
    <div class="user_setting_form">
      <h3 class="user_title">
        アカウント
      </h3>
      <div class="user_setting_form_inner">
        <div class="user_setting_form_row">
          <div class="user_setting_title_area">
            <div class="user_setting_title">メールアドレス</div>
          </div>
          <div class="user_setting_input_area">
            <%= @current_user.email %>
          </div>
        </div>
        <div class="user_setting_form_row">
          <div class="user_setting_title_area">
            <div class="user_setting_title">パスワード</div>
          </div>
          <div class="user_setting_input_area">
            ********
          </div>
        </div>
        <div class="user_setting_form_row">
          <div class="user_setting_title_area" style="position: relative; left: 30%;">
            <%= link_to "編集", edit_user_path(id: @current_user.id), class:"button", id:"user_setting_form_button", style:"margin-right: 10%;" %>
            <%= link_to "削除", @user, method: :delete, data: {confirm: "本当に削除しますか？"}, class:"button", id:"user_setting_form_button" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render "shared/error", obj:@user %>

<div class="edit_container">
  <h1 class="user_edit_title">アカウント編集</h1>
  <div class="edit_form">
    <div class="edit_form_inner">
      <%= form_for(@user, url: users_update_path, method: :post) do |f| %>
        <div class="edit_setting_title"  id="account_edit">メールアドレス</div>
        <div class="edit_setting_input_area" id="account_edit">
          <%= f.email_field :email %>
        </div>
        <div class="edit_setting_title" id="account_edit">変更後パスワード<span class="alert">（変更する場合のみ入力）</span></div>
        <div class="edit_setting_input_area" id="account_edit">
          <%= f.password_field :password %>
        </div>
        <div class="edit_setting_title"  id="account_edit">変更後パスワード確認<span class="alert">（変更する場合のみ入力）</span></div>
        <div class="edit_setting_input_area" id="account_edit">
          <%= f.password_field :password_confirmation %>
        </div>
        <div class="edit_setting_title"  id="account_edit">現在のパスワード</div>
        <div class="edit_setting_input_area" id="account_edit">
          <%= f.password_field :current_password %>
        </div>
        <div class="edit_setting_input_area" style="position: relative; left: 30%;">
          <%= f.submit "更新", class:"button", id:"edit_submit_button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render "shared/error", obj:@user %>
<div class="container" style="display:flex; justify-content:center;">
  <div class="user_form_container">
    <h2 class="form_title">新しいアカウントを作成</h2>
    <div class="form_inner">
      <%= form_with model:@user do |f| %>
        <div class="input_form" id="name_form">
          <div class="mandatory">必須</div>
          <%= f.text_field :name ,placeholder:"ユーザー名" %>
        </div>
        <div class="input_form" id="email_form">
          <div class="mandatory">必須</div>
          <%= f.email_field :email ,placeholder:"メールアドレス" %>
        </div>
        <div class="input_form" id="password_form">
          <div class="mandatory">必須</div>
          <%= f.password_field :password ,placeholder:"パスワード" %>
        </div>
        <div class="input_form" id="password_confirm_form">
          <div class="mandatory">必須</div>
          <%= f.password_field :password_confirmation ,placeholder:"パスワード確認" %>
        </div>
          <%= f.submit "送信", class:"button", id:"submit_login" %>
      <% end %>
      <div class="form_link">
        <%= link_to "すでにアカウントをお持ちの方はログイン", :login %>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<%= render "shared/error", obj:@user %>
<div id="user_setting_container">
  <div class="sidebar">
    <ul>
      <li>
        <%= link_to "アカウント", :users_account %>
      </li>
      <li class="mark">
        <%= link_to "プロフィール", :users_profile %>
      </li>
    </ul>
  </div>
  <div class="main">
    <div class="user_setting_form">
      <h3 class="user_title">
          プロフィール
      </h3>
      <div class="user_setting_form_inner">
        <%= form_for(@user, url: {controller: 'users', action: 'profile_update' }, method: :post) do |f| %>
          <% if @current_user.avatar.attached? %>
            <div class="user_setting_form_row", style ="justify-content:center;" >
              <%= image_tag @current_user.avatar, :alt => "アイコン画像", :class => "user_icon", :size => "100x100" %>
            </div>
          <% else %>
            <div class="user_setting_form_row", style ="justify-content:center;" >
              <%= image_tag "user/default_user.jpg", :alt => "アイコン画像", :class => "user_icon"%>
            </div>
          <% end %>
          <div class="user_setting_form_row">
            <div class="user_setting_title_area">
              <div class="user_setting_title">アイコン画像</div>
            </div>
            <div class="user_setting_input_area">
              <%= f.file_field :avatar %>
            </div>
          </div>
          <div class="user_setting_form_row">
            <div class="user_setting_title_area">
              <div class="user_setting_title">名前</div>
            </div>
            <div class="user_setting_input_area">
              <%= f.text_field :name %>
            </div>
          </div>
          <div class="user_setting_form_row">
            <div class="user_setting_title_area">
              <div class="user_setting_title">自己紹介</div>
            </div>
            <div class="user_setting_input_area">
              <%= f.text_area :introduction %>
            </div>
          </div>
          <div class="user_setting_form_row">
            <div class="user_setting_title_area" style="position: relative; left: 30%;">
              <%= f.submit "更新", class:"button", id:"user_setting_form_button"%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>