config/routes.rb
Rails.application.routes.draw do
  root  :to => 'top#top'
  get    'maps/index'
  get    'posts/index'
  post   'guest_login',                     to: 'guest_sessions#create'
  post   '/search',                         to: 'search#search'
  get    '/login',                          to: 'sessions#new'
  post   '/login',                          to: 'sessions#create'
  delete '/logout',                         to: 'sessions#destroy'
  get    '/users/account',                  to: 'users#account'
  get    '/users/profile',                  to: 'users#profile'
  post   '/users/profile_update',           to: 'users#profile_update'
  get    '/users/edit',                     to: 'users#edit'
  post   '/users/update',                   to: 'users#update'
  get    '/posts/:id/index',                to: 'posts#edit_index'

  resources :users
  resources :posts
  resources :maps, only: [:show]
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true
  validates :image, presence: true
  validates :place_prefecture, presence: true
  validates :place_detail, presence: true
  validates :description, presence: true
  geocoded_by :place_detail
  after_validation :geocode, if: :place_detail_changed?

  scope :latest, -> { order(updated_at: :desc) }

  def self.search(keyword)
    Post
      .where(['title LIKE ? OR description LIKE ? OR place_detail LIKE ?', "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
      .or(Post.where(place_prefecture: keyword.to_s))
  end

  enum place_prefecture: {
    "---": 0,
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
    滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
    沖縄県: 47
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include GuestSessionsHelper
  before_action :logged_in_user
  before_action :guest_check, only: %i[update destroy]

  def index
    gon.map_key = ENV['Google_Map_API']
    @posts = if params[:sort_update]
               Post.latest
             else
               Post.all
             end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(
      **post_params,
      user_id: @current_user.id
    )
    if params[:post][:place_prefecture] == '---'
      flash[:notice] = '目撃場所の都道府県を選択してください'
      render 'posts/new', status: :unprocessable_entity
    elsif @post.save
      flash[:notice] = '目撃情報を投稿しました'
      redirect_to :posts
    else
      render 'posts/new', status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit_index
    if @current_user.id == params[:id].to_i
      @posts = if params[:sort_update]
                 Post.where(user_id: params[:id]).latest
               else
                 Post.where(user_id: params[:id])
               end
      flash[:notice] = '検索結果がありません' if @posts.blank?
    else
      flash[:notice] = '他ユーザーのページにはアクセスできません'
      redirect_to root_path
    end
  end

  def edit
    @post = Post.find(params[:post_id])
  end

  def update
    @post = Post.find(params[:id])
    if params[:post][:place_prefecture] == '---'
      flash[:notice] = '目撃場所の都道府県を選択してください'
      render 'posts/edit', status: :unprocessable_entity
    elsif @post.update(post_params)
      flash[:notice] = '投稿を更新しました'
      redirect_to "/posts/#{@current_user.id}/index"
    else
      flash[:notice] = '更新に失敗しました 入力値が空欄になっていませんか？'
      redirect_to edit_post_path(post_id: @post.id)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = '投稿を削除しました'
    redirect_to "/posts/#{@current_user.id}/index"
  end

  private

  def post_params
    params
      .require(:post)
      .permit(:title, :image, :place_prefecture, :place_detail, :description, :latitude, :longitude)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<%= render "shared/error", obj:@post %>

<div class="edit_container">
  <h1 class="post_top_title">投稿編集</h1>
  <div class="edit_form">
    <div class="edit_form_inner">
      <%= form_with model:@post do |f| %>
        <div class="edit_setting_title">タイトル</div>
        <div class="edit_setting_input_area">
          <%= f.text_field :title, placeholder: @post.title %>
        </div>
        <div class="edit_setting_title">画像</div>
          <%= image_tag @post.image, class: "post_edit_img" %>
          <div class="edit_setting_input_area alert">変更する場合は下記より画像を選んでください</div>
          <div class="edit_setting_input_area">
            <%= f.file_field :image %>
          </div>
        <div class="edit_setting_title">発見場所</div>
        <div class="edit_setting_input_area">
          <%= f.select :place_prefecture, Post.place_prefectures.keys, {} %>
        </div>
        <div class="edit_setting_title">発見場所（詳細位置）</div>
        <div class="edit_setting_input_area">
          <%= f.text_field :place_detail, placeholder: @post.place_detail %>
        </div>
        <div class="edit_setting_title">状況詳細（自由記述）</div>
        <div class="edit_setting_input_area">
          <%= f.text_field :description, placeholder: @post.description %>
        </div>
        <div class="edit_setting_input_area" style="position: relative; left: 30%;">
          <%= f.submit "更新", id:"edit_submit_button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit_index.erb
<h1 class="post_top_title">投稿編集</h1>
<div class="sort_area">
  <%= link_to '投稿順でソートする', "/posts/#{@current_user.id}/index", class: "sort_button" %>
  <%= link_to '新着順でソートする', "/posts/#{@current_user.id}/index?sort_update=true", class: "sort_button" %>
</div>
<div class="container" id="post_index">
  <% @posts.each do |post| %>
    <div class="post_container">
      <div class="post_inner">
        <div class="post_form">
          <div class="post_title">タイトル</div>
            <%= post.title %>
        </div>
        <div class="post_form" id="post_image_form">
          <%= image_tag post.image, class:"post_image" %>
        </div>
        <div class="post_form">
          <div class="post_title">投稿日時</div>
            <%= post.created_at.strftime('%Y/%m/%d %H:%M') %>
        </div>
        <div class="post_form">
          <div class="post_title">発見場所</div>
            <%= post.place_prefecture %>
            <%= post.place_detail %>
        </div>
        <div class="post_form">
          <div class="post_title">状況詳細</div>
            <%= post.description %>
        </div>
        <div class="post_form" id="post_edit_link_container">
          <%= link_to "編集", edit_post_path(post_id: post.id) %>
          <%= link_to "削除", post, method: :delete, data: {confirm: "本当に削除しますか？"} %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<h1 class="post_top_title">みんなが発見した海洋生物情報</h1>
<div class="sort_area">
  <%= link_to '投稿順でソートする', posts_index_path, class: "sort_button" %>
  <%= link_to '新着順でソートする', posts_index_path(sort_update: "true"), class: "sort_button" %>
</div>
<div class="container"id="post_index">
  <% @posts.each do |post| %>
  <div class="post_container">
    <div class="post_inner">
        <div class="post_form">
          <div class="post_title">タイトル</div>
          <%= post.title %>
        </div>
        <div class="post_form" id="post_image_form">
          <%= image_tag post.image, class:"post_image" %>
        </div>
        <div class="post_form">
          <div class="post_title">投稿日時</div>
          <%= post.created_at.strftime('%Y/%m/%d %H:%M') %>
        </div>
        <div class="post_form">
          <div class="post_title">発見場所</div>
          <%= post.place_prefecture %>
          <%= post.place_detail %>
        </div>
        <div class="post_form">
          <div class="post_title">状況詳細</div>
          <%= post.description %>
        </div>
        <div class="post_form">
          <%= link_to "地図で場所を確認する", map_path(post.id) %>
        </div>
    </div>
  </div>
  <% end %>
  <script>
    function connectGoogleMap(){
      var key = gon.map_key
      var sc = document.createElement('script');
      sc.src = `https://maps.googleapis.com/maps/api/js?key=${key}&langage=ja`;
      document.body.appendChild(sc);
    };
    connectGoogleMap();
  </script>
</div>

app/views/posts/new.html.erb
<%= render "shared/error", obj:@post %>
<div class="container" style="display:flex; justify-content:center;">
  <div class="user_form_container">
    <h2 class="form_title">目撃情報を作成</h2>
    <div class="form_inner">
      <%= form_with model:@post do |f| %>
        <div class="input_form" id="name_form">
          <div class="mandatory">必須</div>
          <%= f.text_field :title, placeholder:"タイトル" %>
        </div>
        <div class="input_form" id="image_form">
          <div class="mandatory">必須</div>
          <%= f.file_field :image %>
        </div>
        <div class="input_form select">
          <div class="mandatory">必須</div>
          <%= f.select :place_prefecture, Post.place_prefectures.keys, {} %>
        </div>
        <div class="input_form" id="place_detail_form">
          <div class="mandatory">必須</div>
          <%= f.text_field :place_detail, placeholder:"詳細位置　〇〇市　〇〇海上など" %>
        </div>
        <div class="input_form" id="description_form">
          <div class="mandatory">必須</div>
          <%= f.text_field :description, placeholder:"自由記述" %>
        </div>
          <%= f.submit "送信", class:"button", id:"submit_login" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
<div class="post_container">
  <div class="post_inner">
    <div class="post_form">
      <div class="post_title">タイトル</div>
        <%= @post.title %>
    </div>
    <div class="post_form" id="post_image_form">
      <%= image_tag @post.image %>
    </div>
    <div class="post_form">
      <div class="post_title">発見場所</div>
        <%= @post.place_prefecture %>
        <%= @post.place_detail %>
    </div>
    <div class="post_form">
      <div class="post_title">状況詳細</div>
      <%= @post.description %>
    </div>
  </div>
</div>
</div>